channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - snakemake>=5.10
  - pandas<1  # stay with old pandas
  - matplotlib>=3.1
  - seaborn>=0.9
  - jupyterlab>=2.2
  - altair>=4
  - scikit-bio>=0.5.5
  - scikit-learn>=0.21.3
  - ete3
